server:
  port: 8002
spring:
  application:
    name: UserProvider
  datasource:
    url: jdbc:mysql://db1:3306/springboot-005?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: admin
    password: DEFdef123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/,http://localhost:10087/eureka/
