server:
  port: 8001
spring:
  application:
    name: UserProvider
  datasource:
    url: jdbc:mysql://db1:3306/sprinboot11?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
